# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: "macos-latest"

steps:
  - task: NodeTool@0
    displayName: "Install Node"
    inputs:
      versionSpec: "12.16.1"

  - script: npm install
    workingDirectory: RN_memo
    displayName: "Install node dependencies"

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'RN_memo/android/gradlew'
      workingDirectory: 'RN_memo/android'
      options: '-PversionName=$(Build.BuildNumber) -PversionCode=$(Build.BuildId)'
      tasks: 'assembleRelease'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      gradleOptions: '-Xmx3072m'

  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      apksignerKeystoreFile: 'rn_memo.keystore'
      apksignerKeystorePassword: '$(keystorePassword)'
      apksignerKeystoreAlias: '$(keystoreAlias)'
      apksignerKeyPassword: '$(keystorePassword)'
      zipalign: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'android/app/build/outputs/apk/release'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  # - task: AppCenterDistribute@3
  #   displayName: "Create a release on App Center"
  #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #   inputs:
  #     serverEndpoint: "app-center"
  #     appSlug: "stafford.williams/ReactNativePipeline-Android"
  #     appFile: "ReactNativePipeline$(Build.BuildNumber).apk"
  #     releaseNotesOption: "input"
  #     releaseNotesInput: |
  #       $(Build.SourceVersionMessage)
  #       latest source: '$(Build.SourceVersion)'
  #       An automated release from Azure DevOps
  #     destinationType: "groups"
