# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: "macos-latest"

variables:
  - group: AndroidKeystore

steps:
  - task: NodeTool@0
    displayName: "Install Node"
    inputs:
      versionSpec: "12.16.1"

  - script: npm install
    workingDirectory: RN_memo
    displayName: "Install node dependencies"

  - task: Gradle@2
    inputs:
      workingDirectory: "RN_memo/android"
      gradleWrapperFile: "RN_memo/android/gradlew"
      gradleOptions: "-Xmx3072m"
      publishJUnitResults: false
      testResultsFiles: "**/TEST-*.xml"
      tasks: "bundleRelease"

  - task: AndroidSigning@2
    inputs:
      apkFiles: "RN_memo/android/app/build/outputs/apk/release/app-universal-release.apk"
      jarsign: true
      jarsignerKeystoreFile: "rn_memo.keystore"
      jarsignerKeystorePassword: "$(keystorePassword)"
      jarsignerKeystoreAlias: "my-rn_memo-alias"
      jarsignerKeyPassword: "$(keystorePassword)"
      zipalign: true

  - script: mv RN_memo/android/app/build/outputs/apk/release/app-release-unsigned.apk RN_memo$(Build.BuildNumber).apk
    displayName: "Rename apk"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: RN_memo$(Build.BuildNumber).apk
      artifactName: drop
      publishLocation: "container"

  # - task: AppCenterDistribute@3
  #   displayName: "Create a release on App Center"
  #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #   inputs:
  #     serverEndpoint: "app-center"
  #     appSlug: "stafford.williams/ReactNativePipeline-Android"
  #     appFile: "ReactNativePipeline$(Build.BuildNumber).apk"
  #     releaseNotesOption: "input"
  #     releaseNotesInput: |
  #       $(Build.SourceVersionMessage)

  #       latest source: '$(Build.SourceVersion)'

  #       An automated release from Azure DevOps
  #     destinationType: "groups"
